# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peerServidor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12peerServidor.proto\"-\n\x1aSolicitudPuertoParaUsuario\x12\x0f\n\x07usuario\x18\x01 \x01(\t\"!\n\x0fRespuestaPuerto\x12\x0e\n\x06puerto\x18\x01 \x01(\t\")\n\x16SolicitudPuertoUsuario\x12\x0f\n\x07usuario\x18\x01 \x01(\t\"*\n\x10SolicitudArchivo\x12\x16\n\x0enombre_archivo\x18\x01 \x01(\t\"%\n\x10RespuestaArchivo\x12\x11\n\tcontenido\x18\x01 \x01(\t\"/\n\x15SolicitudCrearArchivo\x12\x16\n\x0enombre_archivo\x18\x01 \x03(\t\"\x1a\n\tRespuesta\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\"&\n\x15RespuestaCrearArchivo\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x32\x9f\x02\n\x12ServicioEntrePeers\x12K\n\x18ObtenerPuertoParaUsuario\x12\x1b.SolicitudPuertoParaUsuario\x1a\x10.RespuestaPuerto\"\x00\x12@\n\x17\x45stablecerPuertoUsuario\x12\x17.SolicitudPuertoUsuario\x1a\n.Respuesta\"\x00\x12\x38\n\x0eObtenerArchivo\x12\x11.SolicitudArchivo\x1a\x11.RespuestaArchivo\"\x00\x12@\n\x0c\x43rearArchivo\x12\x16.SolicitudCrearArchivo\x1a\x16.RespuestaCrearArchivo\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peerServidor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SOLICITUDPUERTOPARAUSUARIO']._serialized_start=22
  _globals['_SOLICITUDPUERTOPARAUSUARIO']._serialized_end=67
  _globals['_RESPUESTAPUERTO']._serialized_start=69
  _globals['_RESPUESTAPUERTO']._serialized_end=102
  _globals['_SOLICITUDPUERTOUSUARIO']._serialized_start=104
  _globals['_SOLICITUDPUERTOUSUARIO']._serialized_end=145
  _globals['_SOLICITUDARCHIVO']._serialized_start=147
  _globals['_SOLICITUDARCHIVO']._serialized_end=189
  _globals['_RESPUESTAARCHIVO']._serialized_start=191
  _globals['_RESPUESTAARCHIVO']._serialized_end=228
  _globals['_SOLICITUDCREARARCHIVO']._serialized_start=230
  _globals['_SOLICITUDCREARARCHIVO']._serialized_end=277
  _globals['_RESPUESTA']._serialized_start=279
  _globals['_RESPUESTA']._serialized_end=305
  _globals['_RESPUESTACREARARCHIVO']._serialized_start=307
  _globals['_RESPUESTACREARARCHIVO']._serialized_end=345
  _globals['_SERVICIOENTREPEERS']._serialized_start=348
  _globals['_SERVICIOENTREPEERS']._serialized_end=635
# @@protoc_insertion_point(module_scope)
